# Generated by Django 4.2.2 on 2023-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('area', models.CharField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('phone', models.CharField()),
                ('distance', models.FloatField()),
                ('img_url', models.CharField()),
                ('address', models.CharField()),
                ('name', models.CharField()),
                ('rating', models.FloatField()),
                ('reviewCount', models.IntegerField()),
                ('yelpLink', models.CharField()),
            ],
        ),
    ]
