# Generated by Django 4.2.2 on 2023-06-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='distance',
        ),
    ]
