# Generated by Django 4.2.2 on 2023-06-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='savedBy',
            new_name='user',
        ),
    ]
