# Generated by Django 4.2.2 on 2023-06-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0006_area_lat_area_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areaCode',
            field=models.CharField(default=None),
        ),
    ]
