# Generated by Django 4.2.2 on 2023-06-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_business_zipseach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='zipSeach',
        ),
    ]
