# Generated by Django 4.2.2 on 2023-06-11 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_business_zipseach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='zipSeach',
            new_name='zipSearch',
        ),
    ]
