# Generated by Django 4.2.2 on 2023-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0012_spot_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(default=None),
        ),
    ]
