# Generated by Django 4.2.2 on 2023-06-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overview', '0013_spot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visted',
        ),
        migrations.AddField(
            model_name='visit',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overview.business'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
