# Generated by Django 4.2.2 on 2023-06-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0015_spot_areaorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overview.business'),
        ),
    ]
