# Generated by Django 4.2.2 on 2023-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0016_spot_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['zipSearch']},
        ),
        migrations.AddField(
            model_name='business',
            name='sourced_by',
            field=models.CharField(default=None),
        ),
    ]
