# Generated by Django 4.2.2 on 2023-07-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0018_business_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='yelpID',
            field=models.CharField(default=False),
        ),
    ]
