# Generated by Django 4.2.2 on 2023-07-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0017_alter_business_options_business_sourced_by'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeleteBusiness',
            new_name='ReportBusiness',
        ),
    ]
