# Generated by Django 4.2.2 on 2023-07-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0017_alter_business_options_business_sourced_by'),
        ('request', '0002_rename_deletebusiness_reportbusiness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddBusiness',
            new_name='AddedBusiness',
        ),
        migrations.RenameModel(
            old_name='ReportBusiness',
            new_name='ReportedBusiness',
        ),
        migrations.AlterModelOptions(
            name='addedbusiness',
            options={'verbose_name_plural': 'Added Businesses'},
        ),
        migrations.AlterModelOptions(
            name='reportedbusiness',
            options={'verbose_name_plural': 'Reported Businesses'},
        ),
    ]
