# Generated by Django 4.2.2 on 2023-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_addbusiness_addedbusiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedbusiness',
            name='yelpID',
            field=models.CharField(default=None),
        ),
    ]
