# Generated by Django 4.2.2 on 2023-07-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_remove_addedbusiness_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedbusiness',
            name='report_message',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportedbusiness',
            name='reported_by',
            field=models.CharField(default=None),
        ),
    ]
