# Generated by Django 4.2.2 on 2023-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_reportedbusiness_report_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedbusiness',
            name='report_message',
            field=models.TextField(default=None),
        ),
    ]
