# Generated by Django 4.2.2 on 2023-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField()),
                ('type', models.CharField()),
                ('area', models.CharField()),
                ('zipSearch', models.CharField(default=None)),
                ('sourced_by', models.CharField(default=None)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField()),
                ('img_url', models.CharField()),
                ('address', models.CharField()),
                ('name', models.CharField()),
                ('rating', models.FloatField()),
                ('reviewCount', models.IntegerField()),
                ('yelpLink', models.CharField()),
            ],
        ),
    ]
